//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubtitleDownloader.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubtitleDownloader.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاگین موردنظر با موفقیت افزوده شد برنامه را مجدد راه اندازی کنید تا تغییرات را مشاهده کنید.
        /// </summary>
        public static string AddedPlugin {
            get {
                return ResourceManager.GetString("AddedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن پلاگین جدید.
        /// </summary>
        public static string AddPlugin {
            get {
                return ResourceManager.GetString("AddPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن برنامه به منوی کلیک راست پوشه ها.
        /// </summary>
        public static string AddToDirectoryContext {
            get {
                return ResourceManager.GetString("AddToDirectoryContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن برنامه به منوی کلیک راست فایل ها.
        /// </summary>
        public static string AddToFileContext {
            get {
                return ResourceManager.GetString("AddToFileContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی لازم را ندارید لطفا برنامه را بصورت ادمین اجرا کنید یا پوشه برنامه را به محل دیگری (خارج از پوشه های سیستمی) منتقل کنید.
        /// </summary>
        public static string AdminError {
            get {
                return ResourceManager.GetString("AdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی.
        /// </summary>
        public static string AdminErrorTitle {
            get {
                return ResourceManager.GetString("AdminErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود خودکار زیرنویس بعد از انتخاب زیرنویس.
        /// </summary>
        public static string AutoDownload {
            get {
                return ResourceManager.GetString("AutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به تغییر زبان برنامه هستید؟.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی بروزرسانی.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب پوشه برای ذخیره....
        /// </summary>
        public static string ChoosePath {
            get {
                return ResourceManager.GetString("ChoosePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد در .
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماژول فعلی : {0}.
        /// </summary>
        public static string CurrentModule {
            get {
                return ResourceManager.GetString("CurrentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه فعلی .
        /// </summary>
        public static string CurrentVer {
            get {
                return ResourceManager.GetString("CurrentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه نویس مهدی حسینی.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دانلود شد.
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...درحال دانلود.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک دانلود.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود بروزرسانی جدید.
        /// </summary>
        public static string DownloadNewVer {
            get {
                return ResourceManager.GetString("DownloadNewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ای سابتایتل.
        /// </summary>
        public static string ESubtitle {
            get {
                return ResourceManager.GetString("ESubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام یا آیدی IMDB فیلم یا سریال را بنویسید... [مثال: tt1442449 یا spartacus].
        /// </summary>
        public static string GetIMDBSearch {
            get {
                return ResourceManager.GetString("GetIMDBSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات فیلم و سریال.
        /// </summary>
        public static string GetMovieInfo {
            get {
                return ResourceManager.GetString("GetMovieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هماهنگی با اینترنت دانلود منیجر (زیرنویس ها با IDM دانلود خواهند شد).
        /// </summary>
        public static string IDM {
            get {
                return ResourceManager.GetString("IDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینترنت دانلود منیجر در سیستم شما پیدا نشد.
        /// </summary>
        public static string IDMNot {
            get {
                return ResourceManager.GetString("IDMNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیگران:.
        /// </summary>
        public static string IMDBActors {
            get {
                return ResourceManager.GetString("IMDBActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوایز:.
        /// </summary>
        public static string IMDBAwards {
            get {
                return ResourceManager.GetString("IMDBAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور:.
        /// </summary>
        public static string IMDBCountry {
            get {
                return ResourceManager.GetString("IMDBCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارگردان:.
        /// </summary>
        public static string IMDBDirector {
            get {
                return ResourceManager.GetString("IMDBDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ژانر:.
        /// </summary>
        public static string IMDBGenre {
            get {
                return ResourceManager.GetString("IMDBGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی:.
        /// </summary>
        public static string IMDBId {
            get {
                return ResourceManager.GetString("IMDBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات IMDB.
        /// </summary>
        public static string ImdbInfo {
            get {
                return ResourceManager.GetString("ImdbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان:.
        /// </summary>
        public static string IMDBLanguage {
            get {
                return ResourceManager.GetString("IMDBLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز متا:.
        /// </summary>
        public static string IMDBMetascore {
            get {
                return ResourceManager.GetString("IMDBMetascore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه داستان:.
        /// </summary>
        public static string IMDBPlot {
            get {
                return ResourceManager.GetString("IMDBPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجه بندی:.
        /// </summary>
        public static string IMDBRated {
            get {
                return ResourceManager.GetString("IMDBRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز:.
        /// </summary>
        public static string IMDBRating {
            get {
                return ResourceManager.GetString("IMDBRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز:.
        /// </summary>
        public static string IMDBRatings {
            get {
                return ResourceManager.GetString("IMDBRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتشار:.
        /// </summary>
        public static string IMDBReleased {
            get {
                return ResourceManager.GetString("IMDBReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع:.
        /// </summary>
        public static string IMDBSource {
            get {
                return ResourceManager.GetString("IMDBSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان:.
        /// </summary>
        public static string IMDBTitle {
            get {
                return ResourceManager.GetString("IMDBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فصل:.
        /// </summary>
        public static string IMDBTotalSeasons {
            get {
                return ResourceManager.GetString("IMDBTotalSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع:.
        /// </summary>
        public static string IMDBType {
            get {
                return ResourceManager.GetString("IMDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز:.
        /// </summary>
        public static string IMDBValue {
            get {
                return ResourceManager.GetString("IMDBValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد رای:.
        /// </summary>
        public static string IMDBVotes {
            get {
                return ResourceManager.GetString("IMDBVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده:.
        /// </summary>
        public static string IMDBWriter {
            get {
                return ResourceManager.GetString("IMDBWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال:.
        /// </summary>
        public static string IMDBYear {
            get {
                return ResourceManager.GetString("IMDBYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string L2R {
            get {
                return ResourceManager.GetString("L2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما از آخرین نسخه استفاده میکنید.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...درحال دریافت اطلاعات.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلم/سریال.
        /// </summary>
        public static string MoSerInfo {
            get {
                return ResourceManager.GetString("MoSerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه جدید .
        /// </summary>
        public static string NewVer {
            get {
                return ResourceManager.GetString("NewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه جدید پیدا شد!.
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ نسخه ای پیدا نشد.
        /// </summary>
        public static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن پوشه.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن پنل.
        /// </summary>
        public static string OpenPanel {
            get {
                return ResourceManager.GetString("OpenPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزونه ها.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرنویس های محبوب.
        /// </summary>
        public static string PopularSub {
            get {
                return ResourceManager.GetString("PopularSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتشار در.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string R2L {
            get {
                return ResourceManager.GetString("R2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرای برنامه در پس زمینه (برنامه به جای بستن مخفی خواهد شد و از سیستم ترای قابل دسترس خواهد بود).
        /// </summary>
        public static string RunInBackground {
            get {
                return ResourceManager.GetString("RunInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه در پس زمینه در حال اجرا خواهد بود و از سیستم ترای قابل دسترس خواهد بود و این پنجره به جای بستن، مخفی خواهد شد. آیا موافقید؟.
        /// </summary>
        public static string RunInBackgroundMainWindow {
            get {
                return ResourceManager.GetString("RunInBackgroundMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string SaveToPc {
            get {
                return ResourceManager.GetString("SaveToPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی زیرنویس....
        /// </summary>
        public static string SearchSub {
            get {
                return ResourceManager.GetString("SearchSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب زبان زیرنویس....
        /// </summary>
        public static string SelectSubLanguage {
            get {
                return ResourceManager.GetString("SelectSubLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب سرور زیرنویس....
        /// </summary>
        public static string SelectSubServer {
            get {
                return ResourceManager.GetString("SelectSubServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور در دسترس نیست.
        /// </summary>
        public static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اطلاعیه هنگام اتمام دانلود.
        /// </summary>
        public static string ShowNotification {
            get {
                return ResourceManager.GetString("ShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر ذخیره.
        /// </summary>
        public static string StoreLoc {
            get {
                return ResourceManager.GetString("StoreLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود زیرنویس.
        /// </summary>
        public static string SubDownload {
            get {
                return ResourceManager.GetString("SubDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان زیرنویس ({0}).
        /// </summary>
        public static string SubLanguage {
            get {
                return ResourceManager.GetString("SubLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرنویس موردنظر پیدا نشد.
        /// </summary>
        public static string SubNotFound {
            get {
                return ResourceManager.GetString("SubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابسین.
        /// </summary>
        public static string Subscene {
            get {
                return ResourceManager.GetString("Subscene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی زیرنویس با اسم یا آی دی Imdb....
        /// </summary>
        public static string SubsceneSearchSub {
            get {
                return ResourceManager.GetString("SubsceneSearchSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور زیرنویس ({0}).
        /// </summary>
        public static string SubServer {
            get {
                return ResourceManager.GetString("SubServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرنویس.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود زیرنویس.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهان زیرنویس.
        /// </summary>
        public static string WorldSub {
            get {
                return ResourceManager.GetString("WorldSub", resourceCulture);
            }
        }
    }
}
