//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandySub.Assets.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandySub.Assets.Strings.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have admin access, please run application as administrator.
        /// </summary>
        public static string AdminError {
            get {
                return ResourceManager.GetString("AdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search History.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location: {0}.
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version {0}.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powerful app for downloading subtitles from subscene and other websites..
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESubtitle.
        /// </summary>
        public static string ESubtitle {
            get {
                return ResourceManager.GetString("ESubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Downloaded.
        /// </summary>
        public static string FileDownloaded {
            get {
                return ResourceManager.GetString("FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Movie/Series Info.
        /// </summary>
        public static string GetMovieInfoIMDB {
            get {
                return ResourceManager.GetString("GetMovieInfoIMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repository.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Download Manager not found on your system.
        /// </summary>
        public static string IDMNot {
            get {
                return ResourceManager.GetString("IDMNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors:.
        /// </summary>
        public static string IMDBActors {
            get {
                return ResourceManager.GetString("IMDBActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string IMDBCountry {
            get {
                return ResourceManager.GetString("IMDBCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director:.
        /// </summary>
        public static string IMDBDirector {
            get {
                return ResourceManager.GetString("IMDBDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string IMDBGenre {
            get {
                return ResourceManager.GetString("IMDBGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string IMDBId {
            get {
                return ResourceManager.GetString("IMDBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string IMDBLanguage {
            get {
                return ResourceManager.GetString("IMDBLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Movie/Series by Name or IMDB Id... [Example tt1442449 or Spartacus].
        /// </summary>
        public static string IMDBPlaceHolder {
            get {
                return ResourceManager.GetString("IMDBPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated:.
        /// </summary>
        public static string IMDBRated {
            get {
                return ResourceManager.GetString("IMDBRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released:.
        /// </summary>
        public static string IMDBReleased {
            get {
                return ResourceManager.GetString("IMDBReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Seasons:.
        /// </summary>
        public static string IMDBTotalSeasons {
            get {
                return ResourceManager.GetString("IMDBTotalSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string IMDBType {
            get {
                return ResourceManager.GetString("IMDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer:.
        /// </summary>
        public static string IMDBWriter {
            get {
                return ResourceManager.GetString("IMDBWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISubtitles.
        /// </summary>
        public static string ISubtitles {
            get {
                return ResourceManager.GetString("ISubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are using Latest Version..
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Search History.
        /// </summary>
        public static string MaxHistory {
            get {
                return ResourceManager.GetString("MaxHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie/Series Info.
        /// </summary>
        public static string MovieInfo {
            get {
                return ResourceManager.GetString("MovieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pane Display Mode.
        /// </summary>
        public static string PaneMode {
            get {
                return ResourceManager.GetString("PaneMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Subtitle by Title or IMDB Id....
        /// </summary>
        public static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a feature.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Accent Color.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To PC.
        /// </summary>
        public static string SaveToPc {
            get {
                return ResourceManager.GetString("SaveToPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Not Found.
        /// </summary>
        public static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Server.
        /// </summary>
        public static string ShellServer {
            get {
                return ResourceManager.GetString("ShellServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subtitle Download Folder.
        /// </summary>
        public static string StoreLocation {
            get {
                return ResourceManager.GetString("StoreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle not found mybe this is a wrong message, so please try again.
        /// </summary>
        public static string SubNotFound {
            get {
                return ResourceManager.GetString("SubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscene.
        /// </summary>
        public static string Subscene {
            get {
                return ResourceManager.GetString("Subscene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscene Server.
        /// </summary>
        public static string SubsceneServer {
            get {
                return ResourceManager.GetString("SubsceneServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found.
        /// </summary>
        public static string SuggestNotFound {
            get {
                return ResourceManager.GetString("SuggestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Back Button.
        /// </summary>
        public static string TGBack {
            get {
                return ResourceManager.GetString("TGBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application To Windows ContextMenu.
        /// </summary>
        public static string TGContext {
            get {
                return ResourceManager.GetString("TGContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download with Internet Download Manager (IDM).
        /// </summary>
        public static string TGIDM {
            get {
                return ResourceManager.GetString("TGIDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification After Download Completed.
        /// </summary>
        public static string TGNotify {
            get {
                return ResourceManager.GetString("TGNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open HandySub with Windows ContextMenu.
        /// </summary>
        public static string TGOpenHandySub {
            get {
                return ResourceManager.GetString("TGOpenHandySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnZip Subtitle After Download Completed.
        /// </summary>
        public static string TGUnzip {
            get {
                return ResourceManager.GetString("TGUnzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we found a new Version, do you want to download?.
        /// </summary>
        public static string VersionFound {
            get {
                return ResourceManager.GetString("VersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Subtitle.
        /// </summary>
        public static string WorldSubtitle {
            get {
                return ResourceManager.GetString("WorldSubtitle", resourceCulture);
            }
        }
    }
}
